name: Add Issues to Nanvix Project

on:
  issues:
    types:
      - opened

permissions:
  contents: read

jobs:
  add-to-project:
    name: Add issue to Nanvix project
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/nanvix/projects/47
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
